name: SonarCloud
on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  sonarcloud_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dockerPostgres123
          POSTGRES_DB: mandacaru_broker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Start PostgreSQL service
        run: docker-compose -f database-docker/docker-compose.yml up -d

      - name: Build and test Spring Boot app
        run: |
          mvn clean install

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=I-Lima_Mandacaru-Broker-API

      - name: Stop PostgreSQL service
        run: docker-compose -f database-docker/docker-compose.yml down
