name: SonarCloud
on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  sonarcloud_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Start PostgreSQL service
        run: cd database-docker && docker-compose up -d

      - name: Build and test Spring Boot app
        run: |
          mvn clean install

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=I-Lima_Mandacaru-Broker-API

      - name: Stop PostgreSQL service
        run: docker-compose -f /database-docker/docker-compose.yml down
